name: Publish release to npm
description: Publish SDK package to npm

inputs:
  node-version:
    description: Node.js version to use
    required: true
  version:
    description: Version being published
    required: true
  require-build:
    description: Whether to build before publishing
    default: true
  release-directory:
    description: Directory to publish from
    default: './'

runs:
  using: composite

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node and npm
      uses: ./.github/actions/setup-node-npm
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: npm ci --include=dev

    - name: Build package
      if: inputs.require-build == 'true'
      shell: bash
      run: npm run build

    - name: Publish release to NPM
      shell: bash
      working-directory: ${{ inputs.release-directory }}
      run: |
        if [[ "${VERSION}" == *"beta"* ]]; then
          TAG="beta"
        elif [[ "${VERSION}" == *"alpha"* ]]; then
          TAG="alpha"
        else
          TAG="latest"
        fi
        npm publish --tag $TAG
      env:
        VERSION: ${{ inputs.version }}
